repos:
### General ###
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-added-large-files
    -   id: fix-encoding-pragma

# ### Secrets ###
# -   repo: https://github.com/Yelp/detect-secrets
#     rev: v0.14.3
#     hooks:
#     -   id: detect-secrets
#         args: ['--baseline', '.secrets.baseline']
#         exclude: .*/hashes/.*

### Formatting ###
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
    -   id: mypy
        args: [relevanceai]
